package com.cqcet.phone.website.pojo;

import java.io.Serializable;

public class Business implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_business.bid
     *
     * @mbggenerated Sat Oct 23 21:47:56 CST 2021
     */
    private String bid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_business.b_name
     *
     * @mbggenerated Sat Oct 23 21:47:56 CST 2021
     */
    private String bName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_business.bkid
     *
     * @mbggenerated Sat Oct 23 21:47:56 CST 2021
     */
    private String bkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_business.comment
     *
     * @mbggenerated Sat Oct 23 21:47:56 CST 2021
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_business
     *
     * @mbggenerated Sat Oct 23 21:47:56 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_business.bid
     *
     * @return the value of t_business.bid
     *
     * @mbggenerated Sat Oct 23 21:47:56 CST 2021
     */
    public String getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_business.bid
     *
     * @param bid the value for t_business.bid
     *
     * @mbggenerated Sat Oct 23 21:47:56 CST 2021
     */
    public void setBid(String bid) {
        this.bid = bid == null ? null : bid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_business.b_name
     *
     * @return the value of t_business.b_name
     *
     * @mbggenerated Sat Oct 23 21:47:56 CST 2021
     */
    public String getbName() {
        return bName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_business.b_name
     *
     * @param bName the value for t_business.b_name
     *
     * @mbggenerated Sat Oct 23 21:47:56 CST 2021
     */
    public void setbName(String bName) {
        this.bName = bName == null ? null : bName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_business.bkid
     *
     * @return the value of t_business.bkid
     *
     * @mbggenerated Sat Oct 23 21:47:56 CST 2021
     */
    public String getBkid() {
        return bkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_business.bkid
     *
     * @param bkid the value for t_business.bkid
     *
     * @mbggenerated Sat Oct 23 21:47:56 CST 2021
     */
    public void setBkid(String bkid) {
        this.bkid = bkid == null ? null : bkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_business.comment
     *
     * @return the value of t_business.comment
     *
     * @mbggenerated Sat Oct 23 21:47:56 CST 2021
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_business.comment
     *
     * @param comment the value for t_business.comment
     *
     * @mbggenerated Sat Oct 23 21:47:56 CST 2021
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}