package com.cqcet.phone.website.pojo;

import java.io.Serializable;

public class Customer implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cus.id
     *
     * @mbggenerated Sat Oct 23 22:08:31 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cus.name
     *
     * @mbggenerated Sat Oct 23 22:08:31 CST 2021
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cus.sex
     *
     * @mbggenerated Sat Oct 23 22:08:31 CST 2021
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cus.tel
     *
     * @mbggenerated Sat Oct 23 22:08:31 CST 2021
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cus.addr
     *
     * @mbggenerated Sat Oct 23 22:08:31 CST 2021
     */
    private String addr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cus.bkid
     *
     * @mbggenerated Sat Oct 23 22:08:31 CST 2021
     */
    private String bkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cus.bid
     *
     * @mbggenerated Sat Oct 23 22:08:31 CST 2021
     */
    private String bid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_cus
     *
     * @mbggenerated Sat Oct 23 22:08:31 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cus.id
     *
     * @return the value of t_cus.id
     *
     * @mbggenerated Sat Oct 23 22:08:31 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cus.id
     *
     * @param id the value for t_cus.id
     *
     * @mbggenerated Sat Oct 23 22:08:31 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cus.name
     *
     * @return the value of t_cus.name
     *
     * @mbggenerated Sat Oct 23 22:08:31 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cus.name
     *
     * @param name the value for t_cus.name
     *
     * @mbggenerated Sat Oct 23 22:08:31 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cus.sex
     *
     * @return the value of t_cus.sex
     *
     * @mbggenerated Sat Oct 23 22:08:31 CST 2021
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cus.sex
     *
     * @param sex the value for t_cus.sex
     *
     * @mbggenerated Sat Oct 23 22:08:31 CST 2021
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cus.tel
     *
     * @return the value of t_cus.tel
     *
     * @mbggenerated Sat Oct 23 22:08:31 CST 2021
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cus.tel
     *
     * @param tel the value for t_cus.tel
     *
     * @mbggenerated Sat Oct 23 22:08:31 CST 2021
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cus.addr
     *
     * @return the value of t_cus.addr
     *
     * @mbggenerated Sat Oct 23 22:08:31 CST 2021
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cus.addr
     *
     * @param addr the value for t_cus.addr
     *
     * @mbggenerated Sat Oct 23 22:08:31 CST 2021
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cus.bkid
     *
     * @return the value of t_cus.bkid
     *
     * @mbggenerated Sat Oct 23 22:08:31 CST 2021
     */
    public String getBkid() {
        return bkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cus.bkid
     *
     * @param bkid the value for t_cus.bkid
     *
     * @mbggenerated Sat Oct 23 22:08:31 CST 2021
     */
    public void setBkid(String bkid) {
        this.bkid = bkid == null ? null : bkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cus.bid
     *
     * @return the value of t_cus.bid
     *
     * @mbggenerated Sat Oct 23 22:08:31 CST 2021
     */
    public String getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cus.bid
     *
     * @param bid the value for t_cus.bid
     *
     * @mbggenerated Sat Oct 23 22:08:31 CST 2021
     */
    public void setBid(String bid) {
        this.bid = bid == null ? null : bid.trim();
    }
}