package com.cqcet.phone.website.pojo;

import java.io.Serializable;

public class Kind implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bkinds.bkid
     *
     * @mbggenerated Sat Oct 23 21:47:56 CST 2021
     */
    private String bkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bkinds.bk_name
     *
     * @mbggenerated Sat Oct 23 21:47:56 CST 2021
     */
    private String bkName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bkinds.comment
     *
     * @mbggenerated Sat Oct 23 21:47:56 CST 2021
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_bkinds
     *
     * @mbggenerated Sat Oct 23 21:47:56 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bkinds.bkid
     *
     * @return the value of t_bkinds.bkid
     *
     * @mbggenerated Sat Oct 23 21:47:56 CST 2021
     */
    public String getBkid() {
        return bkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bkinds.bkid
     *
     * @param bkid the value for t_bkinds.bkid
     *
     * @mbggenerated Sat Oct 23 21:47:56 CST 2021
     */
    public void setBkid(String bkid) {
        this.bkid = bkid == null ? null : bkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bkinds.bk_name
     *
     * @return the value of t_bkinds.bk_name
     *
     * @mbggenerated Sat Oct 23 21:47:56 CST 2021
     */
    public String getBkName() {
        return bkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bkinds.bk_name
     *
     * @param bkName the value for t_bkinds.bk_name
     *
     * @mbggenerated Sat Oct 23 21:47:56 CST 2021
     */
    public void setBkName(String bkName) {
        this.bkName = bkName == null ? null : bkName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bkinds.comment
     *
     * @return the value of t_bkinds.comment
     *
     * @mbggenerated Sat Oct 23 21:47:56 CST 2021
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bkinds.comment
     *
     * @param comment the value for t_bkinds.comment
     *
     * @mbggenerated Sat Oct 23 21:47:56 CST 2021
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}