package com.cqcet.phone.website.mapper;

import com.cqcet.phone.website.pojo.Business;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BusinessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business
     *
     * @mbggenerated Sat Oct 23 21:47:56 CST 2021
     */
    int deleteByPrimaryKey(String bid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business
     *
     * @mbggenerated Sat Oct 23 21:47:56 CST 2021
     */
    int insert(Business record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business
     *
     * @mbggenerated Sat Oct 23 21:47:56 CST 2021
     */
    int insertSelective(Business record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business
     *
     * @mbggenerated Sat Oct 23 21:47:56 CST 2021
     */
    Business selectByPrimaryKey(String bid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business
     *
     * @mbggenerated Sat Oct 23 21:47:56 CST 2021
     */
    int updateByPrimaryKeySelective(Business record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business
     *
     * @mbggenerated Sat Oct 23 21:47:56 CST 2021
     */
    int updateByPrimaryKey(Business record);

    List<Business> selectByForeignKey(String bKid);

    List<Business> selectByAll();

    List<Business> selectBySelective(@Param("bid") String bid, @Param("bName") String bName);
}