package com.cqcet.phone.website.mapper;

import com.cqcet.phone.website.pojo.Customer;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cus
     *
     * @mbggenerated Sat Oct 23 22:08:31 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cus
     *
     * @mbggenerated Sat Oct 23 22:08:31 CST 2021
     */
    int insert(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cus
     *
     * @mbggenerated Sat Oct 23 22:08:31 CST 2021
     */
    int insertSelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cus
     *
     * @mbggenerated Sat Oct 23 22:08:31 CST 2021
     */
    Customer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cus
     *
     * @mbggenerated Sat Oct 23 22:08:31 CST 2021
     */
    int updateByPrimaryKeySelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cus
     *
     * @mbggenerated Sat Oct 23 22:08:31 CST 2021
     */
    int updateByPrimaryKey(Customer record);

    Customer selectBySelective(@Param("id") String id, @Param("userName") String userName,@Param("tel") String tel,@Param("bid") String bid);

    List<Customer> selectByAllSelective(@Param("id") String id, @Param("userName") String userName,@Param("tel") String tel,@Param("bid") String bid);

    List<Customer> selectAll();

    int updateByBKId(String id);
}