package com.cqcet.phone.website.mapper;

import com.cqcet.phone.website.pojo.Kind;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface KindMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bkinds
     *
     * @mbggenerated Sat Oct 23 21:47:56 CST 2021
     */
    int deleteByPrimaryKey(String bkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bkinds
     *
     * @mbggenerated Sat Oct 23 21:47:56 CST 2021
     */
    int insert(Kind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bkinds
     *
     * @mbggenerated Sat Oct 23 21:47:56 CST 2021
     */
    int insertSelective(Kind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bkinds
     *
     * @mbggenerated Sat Oct 23 21:47:56 CST 2021
     */
    Kind selectByPrimaryKey(String bkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bkinds
     *
     * @mbggenerated Sat Oct 23 21:47:56 CST 2021
     */
    int updateByPrimaryKeySelective(Kind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bkinds
     *
     * @mbggenerated Sat Oct 23 21:47:56 CST 2021
     */
    int updateByPrimaryKey(Kind record);

    List<Kind> selectAllKind();

    List<Kind> selectBySelective(@Param("bkid") String bkid,@Param("bkName") String bkName);
}